prsb/band/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# urls.py
# Author: Jim Andress
# Created: 4/28/24
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = "band"
urlpatterns = [
    path("accounts/login/", LoginView.as_view(template_name="band/registration/login.html")),
    path("accounts/logout/", LogoutView.as_view(next_page="login"), name="logout"),

    path("", views.index, name='index'),

    path("members/", views.MemberListView.as_view(), name="member_list"),
    path("members/<int:pk>/", views.MemberDetailView.as_view(), name="member_detail"),
    # path("members/<int:pk>/update/", views.MemberUpdateView.as_view(), name="member_update"),
    path("members/<int:member_id>/part-assignments/create/", views.MemberPartAssignmentCreateView.as_view(), name='member_part_assignment_create'),
    path("members/<int:member_id>/part-assignments/<int:pk>/update/",
         views.MemberPartAssignmentUpdateView.as_view(), name="member_part_assignment_update"),

    path("songs/", views.SongListView.as_view(), name="song_list"),
    path("songs/create/", views.SongCreateView.as_view(), name="song_create"),
    path("songs/<int:pk>/", views.SongDetailView.as_view(), name="song_detail"),
    path("songs/<int:pk>/update/", views.SongUpdateView.as_view(), name="song_update"),
    path("songs/<int:song_id>/part-assignments/create/", views.SongPartAssignmentCreateView.as_view(), name='song_part_assignment_create'),
    path("songs/<int:song_id>/part-assignments/<int:pk>/update/",
         views.SongPartAssignmentUpdateView.as_view(), name="song_part_assignment_update"),

    path("part-assignments/", views.PartAssignmentListView.as_view(), name="part_assignment_list"),
    path("part-assignments/create/", views.PartAssignmentCreateView.as_view(), name="part_assignment_create"),
    path("part-assignments/<int:pk>/update/", views.PartAssignmentUpdateView.as_view(), name="part_assignment_update"),

    path("gigs/", views.GigListView.as_view(), name="gig_list"),
    path("gigs/create/", views.GigCreateView.as_view(), name="gig_create"),
    path("gigs/<int:pk>/", views.GigDetailView.as_view(), name="gig_detail"),
    path("gigs/<int:pk>/update/", views.GigUpdateView.as_view(), name="gig_update"),
    path("gigs/<int:gig_id>/availability/update", views.GigAvailabilityUpdateView.as_view(), name="gig_availability_update"),
    path("gigs/<int:pk>/gig-part-assignments/", views.GigPartAssignmentsDetailView.as_view(), name="gig_part_assignments_detail"),
    path("gigs/<int:pk>/gig-part-assignments/create", views.GigPartAssignmentOverrideCreateView.as_view(), name="gig_part_assignment_override_create"),
    path("gigs/<int:pk>/gig-part-assignments/print", views.GigPartAssignmentPrintView.as_view(), name="gig_part_assignment_print"),
    path("gigs/<int:gig_id>/setlist/update", views.GigSetlistUpdateView.as_view(), name="gig_setlist_update"),
    path("gigs/<int:gig_id>/setlist/add-song/<int:song_id>", views.GigSetlistAddSongView.as_view(), name='gig_setlist_add_song'),

    path("instruments/", views.InstrumentListView.as_view(), name="instrument_list"),

    path("health/", views.health_check),

    path('api/instruments/', views.get_instruments, name='api_instruments'),
]

prsb/prsb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("band.urls")),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

prsb/band/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from djangoyearlessdate.models import YearlessDateField
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
from ordered_model.models import OrderedModel
from tinymce import models as tinymce_models


class Song(models.Model):
    title = models.CharField(max_length=256)
    composer = models.CharField(max_length=256, blank=True)
    duration = models.DurationField(null=True, blank=True)
    in_gig_rotation = models.BooleanField(default=False)
    form = models.CharField(max_length=256, blank=True)

    class Meta:
        ordering = ["title"]

    def get_absolute_url(self):
        return reverse("band:song_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title


class SongPart(models.Model):
    song = models.ForeignKey(Song, related_name='parts', on_delete=models.CASCADE)
    name = models.CharField(max_length=256)

    class Meta:
        order_with_respect_to = 'song'

    def __str__(self):
        return f'{self.song.title}: {self.name}'

    def get_order(self) -> int:
        return self._order


class BandMember(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)

    phone_number = PhoneNumberField(null=True, blank=True)

    emergency_contact_name = models.CharField(max_length=256, blank=True)
    emergency_contact_phone = PhoneNumberField(null=True, blank=True)

    bio = tinymce_models.HTMLField(blank=True)
    birthday = YearlessDateField(null=True, blank=True)
    dietary_restrictions = models.TextField(blank=True)
    tshirt_size = models.CharField(max_length=256, blank=True)

    class Meta:
        ordering = ["user__first_name", "user__last_name"]

    def __str__(self):
        return self.user.get_full_name()


@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        BandMember.objects.create(user=instance)
    instance.bandmember.save()


class Instrument(OrderedModel):
    name = models.CharField(max_length=256)
    quantity = models.PositiveSmallIntegerField(default=1)
    include_in_gig_song_count = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class PerformanceReadiness:
    READY = "ready"
    BACKUP = "backup"
    NOT_READY = "not_ready"
    CHOICES = {
        READY: "Ready to Perform",
        BACKUP: "Can Perform as Backup",
        NOT_READY: "Not Ready to Perform"
    }
    CHOICES_OVERRIDES = {
        READY: "Ready to Perform",
        BACKUP: "Can Perform as Backup"
    }


class PartAssignment(models.Model):
    member = models.ForeignKey(BandMember, on_delete=models.CASCADE)
    song_part = models.ForeignKey(SongPart, on_delete=models.CASCADE)
    instrument = models.ForeignKey(Instrument, on_delete=models.CASCADE)
    performance_readiness = models.CharField(max_length=256,
                                             choices=PerformanceReadiness.CHOICES,
                                             default=PerformanceReadiness.READY)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['member', 'song_part', 'instrument'], name='unique PartAssignment')
        ]

    def __str__(self):
        return f'{self.member} plays {self.instrument} on {self.song_part}'

    def is_backup(self) -> bool:
        return self.performance_readiness == PerformanceReadiness.BACKUP

    def is_not_ready(self) -> bool:
        return self.performance_readiness == PerformanceReadiness.NOT_READY


class Gig(models.Model):
    name = models.CharField(max_length=256)
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()

    address = models.CharField(blank=True)

    notes = tinymce_models.HTMLField(blank=True)

    def clean(self):
        super().clean()
        if self.end_datetime <= self.start_datetime:
            raise ValidationError("A gig cannot end before it begins.")

    class Meta:
        ordering = ["-start_datetime"]

    def __str__(self):
        return self.name


class GigSetlistEntry(models.Model):
    gig = models.ForeignKey(Gig, on_delete=models.CASCADE)

    song = models.ForeignKey(Song, on_delete=models.CASCADE, null=True, blank=True)
    break_duration = models.DurationField(null=True, blank=True)

    @property
    def is_break(self) -> bool:
        return self.song is None

    def clean(self):
        super().clean()
        if self.song is not None and self.break_duration is not None:
            raise ValidationError("A setlist entry should be either a song or a break, not both")
        if self.song is None and self.break_duration is None:
            raise ValidationError("A setlist entry needs to be either a song or a break")

    class Meta:
        order_with_respect_to = 'gig'


class GigInstrument(models.Model):
    gig = models.ForeignKey(Gig, on_delete=models.CASCADE)
    instrument = models.ForeignKey(Instrument, on_delete=models.CASCADE)
    gig_quantity = models.PositiveSmallIntegerField(default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['gig', 'instrument'], name='unique GigInstrument', violation_error_message='The instrument is already assigned to this gig.')
        ]
        ordering = ["instrument__order"]

    def __str__(self):
        return f'{self.gig}: {self.instrument}'


class GigAttendance(models.Model):
    AVAILABLE = "available"
    UNAVAILABLE = "unavailable"
    MAYBE_AVAILABLE = "maybe_available"
    AVAILABILITY_CHOICES = {
        AVAILABLE: "Available",
        MAYBE_AVAILABLE: "Maybe Available",
        UNAVAILABLE: "Unavailable"
    }

    gig = models.ForeignKey(Gig, on_delete=models.CASCADE)
    member = models.ForeignKey(BandMember, on_delete=models.CASCADE)
    status = models.CharField(max_length=256, choices=AVAILABILITY_CHOICES)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['gig', 'member'], name='unique GigAttendance')
        ]

    def __str__(self):
        return f'{self.gig}: {self.member} ({self.status})'


class GigPartAssignmentOverride(models.Model):
    member = models.ForeignKey(BandMember, on_delete=models.CASCADE)
    song_part = models.ForeignKey(SongPart, on_delete=models.CASCADE)
    gig_instrument = models.ForeignKey(GigInstrument, on_delete=models.CASCADE)
    performance_readiness = models.CharField(max_length=256,
                                             choices=PerformanceReadiness.CHOICES_OVERRIDES,
                                             default=PerformanceReadiness.READY)

    def __str__(self):
        return f'{self.member} plays {self.gig_instrument.instrument} on {self.song_part} at {self.gig_instrument.gig}'

    def clean(self):
        super().clean()
        if GigPartAssignmentOverride.objects.filter(member=self.member,
                                                    gig_instrument__gig=self.gig_instrument.gig,
                                                    song_part__song=self.song_part.song).exclude(pk=self.pk).exists():
            raise ValidationError("A band member can only have one override per song per gig")


class BandSpecialDate(models.Model):
    date = YearlessDateField()
    description = models.TextField()

    def __str__(self):
        return f'{self.date}: {self.description}'

    class Meta:
        ordering = ['date']

prsb/band/templates/band/bandmember_detail.html
{% extends "band/base.html" %}

{% block title %}{{ bandmember }} | PRSB{% endblock %}

{% block nav %}
    <a href={% url 'band:index' %}>Home</a>
    > <a href={% url 'band:member_list' %}>Band Members</a>
    > {{ bandmember }}
{% endblock %}

{% block content %}
    <h1>{{ bandmember }}</h1>

    <div>
        <p>Username: {{ bandmember.user.username }}</p>
    </div>

{#    <div>#}
{#        <h2>Contact Info</h2>#}
{#        <p>Email: {{ bandmember.user.email }}</p>#}
{#        <p>Phone Number: {{ bandmember.phone_number }}</p>#}
{#    </div>#}
{##}
{#    <div>#}
{#        <h2>Emergency Contact</h2>#}
{#        <p>Name: {{ bandmember.emergency_contact_name }}</p>#}
{#        <p>Phone Number: {{ bandmember.emergency_contact_phone }}</p>#}
{#    </div>#}
{##}
{#    <div>#}
{#        <h2>Other Information</h2>#}
{#        <p>Bio: {{ bandmember.bio|safe }}</p>#}
{#        <p>Birthday: {{ bandmember.birthday|date:"F j" }}</p>#}
{#        <p>Dietary Restrictions: {{ bandmember.dietary_restrictions }}</p>#}
{#        <p>T-Shirt Size: {{ bandmember.tshirt_size }}</p>#}
{#    </div>#}

    <div>
        <h2>Part Assignments</h2>

        <a href={% url 'band:member_part_assignment_create' bandmember.pk %}>New Part Assignment</a>

        <table class="sortable">
            <thead>
                <tr>
                    <th>Song</th>
                    <th>Part</th>
                    <th>Instrument</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                {% for part_assignment in part_assignments %}
                    <tr {% if part_assignment.is_backup %} class="warning" {% elif part_assignment.is_not_ready %} class="error" {% endif %}>
                        <td>{{ part_assignment.song_part.song }}</td>
                        <td sorttable_customkey={{ part_assignment.song_part.get_order }}>{{ part_assignment.song_part.name }}</td>
                        <td sorttable_customkey={{ part_assignment.instrument.order }}>{{ part_assignment.instrument }}</td>
                        <td><a href={% url 'band:member_part_assignment_update' member_id=part_assignment.member.pk pk=part_assignment.pk %}>Edit</a></td>
                    </tr>
                {% endfor %}

                {% for missing_song in missing_songs %}
                    <tr>
                        <td>{{ missing_song }}</td>
                        <td sorttable_customkey=100></td>
                        <td sorttable_customkey=100></td>
                        <td></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div>
        <h2>Upcoming Gigs</h2>
        <ul>
            {% for attendance in upcoming_gig_attendance %}
                <li>{{ attendance.gig }}: {{ attendance.status }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

prsb/band/templates/band/gig_availability_update.html
{% extends "band/base.html" %}

{% block title %}{{ gig.name }} Member Availability | PRSB{% endblock %}

{% block nav %}
    <a href={% url 'band:index' %}>Home</a>
    > <a href={% url 'band:gig_list' %}>Gigs</a>
    > <a href={% url 'band:gig_detail' gig.id %}>{{ gig.name }}</a>
    > Update Member Availability
{% endblock %}

{% block content %}
    <h1>{{ gig.name }} Band Member Availability</h1>
    <form method="post">
        {% csrf_token %}
        {{ formset.management_form }}

        <table>
            <thead>
                <th>Member</th>
                <th>Availability</th>
            </thead>
            <tbody>
                {% for form in formset %}
                    <tr>
                        {{ form.attendance_id }}
                        {{ form.member_id }}
                        <td>{{ form.member_name }}</td>
                        <td>{{ form.status }}</td>
                    </tr>
            {% endfor %}
            </tbody>
        </table>
        <input type="submit" value="Update">
    </form>
{% endblock %}

prsb/band/templates/band/gig_detail.html
{% extends "band/base.html" %}
{% load tz %}
{% load custom_filters %}

{% block title %}{{ gig.name }} | PRSB{% endblock %}

{% block nav %}
    <a href={% url 'band:index' %}>Home</a>
    > <a href={% url 'band:gig_list' %}>Gigs</a>
    > {{ gig.name }}
{% endblock %}

{% block content %}
    <h1>{{gig.name}}</h1>
    <a href={% url 'band:gig_update' gig.id %}>Edit Gig Information</a>
    <p>Start: {{ gig.start_datetime|localtime }}</p>
    <p>End: {{ gig.end_datetime|localtime }}</p>
    <p>Address: {{ gig.address }}</p>
    <p>{{ gig.notes|safe }}</p>

    <h2>Band Member Availability</h2>
    <a href={% url 'band:gig_availability_update' gig.id %}>Edit Member Availability</a>
    <table>
        <thead>
            <tr>
                <th>Available ({{ available_members | length }})</th>
                <th>Maybe Available ({{ maybe_available_members | length }})</th>
                <th>Not Available ({{ unavailable_members | length }})</th>
                <th>Missing Availability ({{ missing_members | length }})</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    {% for attendance in available_members %}
                        {{ attendance.member }}
                        <br/>
                    {% endfor %}
                </td>
                <td>
                    {% for attendance in maybe_available_members %}
                        {{ attendance.member }}
                        <br/>
                    {% endfor %}
                </td>
                <td>
                    {% for attendance in unavailable_members %}
                        {{ attendance.member }}
                        <br/>
                    {% endfor %}
                </td>
                <td>
                    {% for member in missing_members %}
                        {{ member }}
                        <br/>
                    {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    <h2>Setlist</h2>
    <a href={% url 'band:gig_setlist_update' gig.id %}>Edit Setlist</a>
    <ol>
        {% for set_list_entry in setlist %}
            <li>{% if set_list_entry.song %}
                    {{ set_list_entry.song }} ({{ set_list_entry.song.duration|duration_to_minutes_seconds }})
                {% else %}
                    Break ({{ set_list_entry.break_duration|duration_to_minutes_seconds }})
                {% endif %}
            </li>
        {% endfor %}
    </ol>

    {% if setlist|length > 0 %}
        Music: {{ music_duration|duration_to_minutes_seconds }}
    {% endif %}

    {% if total_duration %}
        <br>
        Total: {{ total_duration|duration_to_minutes_seconds }}
    {% endif %}

    <h2>Instruments</h2>
    <ul>
        {% for gig_instrument in gig.giginstrument_set.all %}
            <li>{{ gig_instrument.instrument }} ({{ gig_instrument.gig_quantity }})</li>
        {% endfor %}
    </ul>

    <h2>Part Assignments</h2>
    <p>
        <a href={% url 'band:gig_part_assignments_detail' gig.id %}>See Part Assignments</a>
    </p>
{% endblock %}

prsb/band/templates/band/gig_list.html
{% extends "band/base.html" %}
{% load tz %}qq

{% block title %}Gigs | PRSB{% endblock %}

{% block nav %}
    <a href={% url 'band:index' %}>Home</a>
    > Gigs
{% endblock %}

{% block content %}
    <h2>Gigs</h2>

    <a href={% url 'band:gig_create' %}>New Gig</a>

    <h3>Upcoming Gigs</h3>
    <ul>
        {% for gig in upcoming_gigs %}
            <li><a href={% url 'band:gig_detail' gig.id %}>{{ gig }} ({{ gig.start_datetime|localtime|date:"Y-m-d" }})</a></li>
        {% endfor %}
    </ul>

    <h3>Past Gigs</h3>
    <ul>
        {% for gig in past_gigs %}
            <li><a href={% url 'band:gig_detail' gig.id %}>{{ gig }} ({{ gig.start_datetime|localtime|date:"Y-m-d" }})</a></li>
        {% endfor %}
    </ul>
{% endblock %}

prsb/band/templates/band/gig_part_assignments.html
{% extends "band/base.html" %}
{% load tz %}

{% block title %}{{ gig.name }} | Part Assignments | PRSB{% endblock %}

{% block nav %}
    <a href={% url 'band:index' %}>Home</a>
    > <a href={% url 'band:gig_list' %}>Gigs</a>
    > <a href={% url 'band:gig_detail' gig.id %}>{{ gig.name }}</a>
    > Part Assignments
{% endblock %}

{% block content %}
    <h1>{{gig.name}}</h1>

    <h2>Part Assignment Overrides</h2>
    <a href={% url 'band:gig_part_assignment_override_create' gig.id %}>Add new Part Assignment Override</a>
    {% if part_assignment_overrides %}
        <table class="sortable">
            <thead>
                <tr>
                    <th>Song</th>
                    <th>Part</th>
                    <th>Instrument</th>
                    <th>Band Member</th>
                </tr>
            </thead>
            <tbody>
                {% for pao in part_assignment_overrides %}
                    <tr>
                        <td>{{ pao.song_part.song }}</td>
                        <td sorttable_customkey={{ pao.song_part.get_order }}>{{ pao.song_part }}</td>
                        <td sorttable_customkey={{ pao.gig_instrument.instrument.order }}>{{ pao.gig_instrument.instrument }}</td>
                        <td>{{ pao.member }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}

    {% if gig_part_assignments_setlist|length > 0 %}
        <h2>Setlist Songs</h2>
        {% for gpa in gig_part_assignments_setlist %}
            <details>
                <summary>{{ gpa.song.title }}</summary>

                <table class="sortable">
                    <thead>
                        <tr>
                            <th>Part</th>
                            <th>Instrument</th>
                            <th>Band Member</th>
                        </tr>
                    </thead>
                    <tbody>
    {#                     the song parts not being played#}
                        {% for song_part in gpa.unplayed_parts %}
                            <tr class="error">
                                <td sorttable_customkey={{ song_part.get_order }}>{{ song_part }}</td>
                                <td sorttable_customkey=100></td>
                                <td></td>
                            </tr>
                        {% endfor %}

    {#                     the people playing parts#}
                        {% for part_assignment in gpa.part_assignments %}
                            <tr {% if part_assignment.is_backup %} class="warning" {% endif %}>
                                <td sorttable_customkey={{ part_assignment.song_part.get_order }}>{{ part_assignment.song_part }}</td>
                                <td sorttable_customkey={{ part_assignment.instrument.order }}>{{ part_assignment.instrument }}</td>
                                <td>{{ part_assignment.member }}</td>
                            </tr>
                        {% endfor %}

    {#                     the members not playing#}
                        {% for member in gpa.non_players %}
                            <tr class="unutilized-row">
                                <td sorttable_customkey=100></td>
                                <td sorttable_customkey=100></td>
                                <td>{{ member }}</td>
                            </tr>
                        {% endfor %}

    {#                     the instruments not being played#}
                        {% for instrument, cnt in gpa.unplayed_instruments.items %}
                            <tr class="unutilized-row">
                                <td sorttable_customkey=100></td>
                                <td sorttable_customkey={{ instrument.order }}>{{ instrument }} ({{ cnt }})</td>
                                <td></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </details>
        {% endfor %}
    {% endif %}

    <h2>Song Recommendations</h2>
    {% for gpa in gig_part_assignments_recs %}
        <details>
            <summary>{{ gpa.song.title }} ({{ gpa.score|floatformat:2 }})</summary>

            <table class="sortable">
                <thead>
                    <tr>
                        <th>Part</th>
                        <th>Instrument</th>
                        <th>Band Member</th>
                    </tr>
                </thead>
                <tbody>
{#                     the song parts not being played#}
                    {% for song_part in gpa.unplayed_parts %}
                        <tr class="error">
                            <td sorttable_customkey={{ song_part.get_order }}>{{ song_part }}</td>
                            <td sorttable_customkey=100></td>
                            <td></td>
                        </tr>
                    {% endfor %}

{#                     the people playing parts#}
                    {% for part_assignment in gpa.part_assignments %}
                        <tr {% if part_assignment.is_backup %} class="warning" {% endif %}>
                            <td sorttable_customkey={{ part_assignment.song_part.get_order }}>{{ part_assignment.song_part }}</td>
                            <td sorttable_customkey={{ part_assignment.instrument.order }}>{{ part_assignment.instrument }}</td>
                            <td>{{ part_assignment.member }}</td>
                        </tr>
                    {% endfor %}

{#                     the members not playing#}
                    {% for member in gpa.non_players %}
                        <tr class="unutilized-row">
                            <td sorttable_customkey=100></td>
                            <td sorttable_customkey=100></td>
                            <td>{{ member }}</td>
                        </tr>
                    {% endfor %}

{#                     the instruments not being played#}
                    {% for instrument, cnt in gpa.unplayed_instruments.items %}
                        <tr class="unutilized-row">
                            <td sorttable_customkey=100></td>
                            <td sorttable_customkey={{ instrument.order }}>{{ instrument }} ({{ cnt }})</td>
                            <td></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <a href={% url 'band:gig_setlist_add_song' gig_id=gig.id song_id=gpa.song.id %}>Add to Setlist</a>
        </details>
    {% endfor %}

    <h2>Number of Songs per Person</h2>
    <table class="sortable">
        <thead>
            <tr>
                <th>Band Member</th>
                <th>Number of Songs</th>
            </tr>
        </thead>
        <tbody>
            {% for member, cnt in member_song_counts %}
                <tr>
                    <td>{{ member }}</td>
                    <td>{{ cnt }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <h2>Options and Settings</h2>
    <div>
        <p>
            <a href="{% url 'band:gig_part_assignment_print' gig.id %}?order=setlist">Print Setlist Part Assignments</a>
        </p>
        <p>
            <label for="hide-unutilized">Hide Unutilized:</label>
            <input type="checkbox" id="hide-unutilized" checked>
        </p>
    </div>
{% endblock %}

{% block extra_js %}
<script>
    function toggleUnutilizedRows() {
        document.querySelectorAll(".unutilized-row").forEach(row => {
            row.style.display = document.getElementById("hide-unutilized").checked ? "none" : "";
        });
    }

    // Hide unutilized rows on page load
    toggleUnutilizedRows();

    // Add event listener for checkbox change
    document.getElementById("hide-unutilized").addEventListener("change", toggleUnutilizedRows);
</script>
{% endblock %}

prsb/band/templates/band/gigpartassignmentoverride_create_form.html
{% extends "band/base.html" %}

{% block title %}New Gig Part Assignment Override | PRSB{% endblock %}

{% block nav %}
    <a href={% url 'band:index' %}>Home</a>
    > <a href={% url 'band:gig_list' %}>Gigs</a>
    > <a href={% url 'band:gig_detail' form.gig_id %}>{{ form.gig_name }}</a>
    > <a href={% url 'band:gig_part_assignments_detail' form.gig_id %}>Part Assignments</a>
    > New Gig Part Assignment Override
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

prsb/band/templates/band/instrument_list.html
{% extends "band/base.html" %}

{% block title %}Instruments | PRSB{% endblock %}

{% block nav %}
    <a href={% url 'band:index' %}>Home</a>
    > Instruments
{% endblock %}

{% block content %}
    <h2>Instruments</h2>
    <ul>
        {% for instrument in object_list %}
            <li>{{ instrument.name }} (x{{ instrument.quantity }})</li>
        {% endfor %}
    </ul>
{% endblock %}

prsb/band/templates/band/partassignment_update_form.html
{% extends "band/base.html" %}

{% block title %}{{ partassignment }} | Update | PRSB{% endblock %}

{% block nav %}
    <a href={% url 'band:index' %}>Home</a>
    {% if form.member_name %}
        > <a href={% url 'band:member_list' %}>Band Members</a>
        > <a href={% url 'band:member_detail' form.member_id %}>{{ form.member_name }}</a>
    {% elif form.song_name %}
        > <a href={% url 'band:song_list' %}>Songs</a>
        > <a href={% url 'band:song_detail' form.song_id %}>{{ form.song_name }}</a>
    {% else %}
        > <a href={% url 'band:part_assignment_list' %}>Part Assignments</a>
    {% endif %}
    > Update Part Assignment
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

prsb/band/templates/band/song_list.html
{% extends "band/base.html" %}

{% block title %}Songs | PRSB{% endblock %}

{% block nav %}
    <a href={% url 'band:index' %}>Home</a>
    > Songs
{% endblock %}

{% block content %}
    <h2>Songs</h2>
    <a href={% url 'band:song_create' %}>New Song</a>
    <ul>
        {% for song in object_list %}
            <li><a href={% url 'band:song_detail' song.id %}>{{ song.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

prsb/band/templates/band/song_update_form.html
{% extends "band/base.html" %}

{% block title %}{{ song.title }} | Update | PRSB{% endblock %}

{% block nav %}
    <a href={% url 'band:index' %}>Home</a>
    > <a href={% url 'band:song_list' %}>Songs</a>
    > <a href={% url 'band:song_detail' song.id %}>{{ song.title }}</a>
    > Update
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}